<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\City;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $cities = [
            [ 'id' => 1, 'name' => 'Abapó', 'state_id' => 3, 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 2, 'state_id' => 3, 'name' => 'Ascención de Guarayos', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 3, 'state_id' => 3, 'name' => 'Ascensión', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 4, 'state_id' => 3, 'name' => 'Boyuibe', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 5, 'state_id' => 3, 'name' => 'Buena Vista', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 6, 'state_id' => 3, 'name' => 'Camiri', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 7, 'state_id' => 3, 'name' => 'Charagua', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 8, 'state_id' => 3, 'name' => 'Comarapa', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 9, 'state_id' => 3, 'name' => 'Concepción', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 10, 'state_id' => 1, 'name' => 'Guayaramerín', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 11, 'state_id' => 1, 'name' => 'Provincia Cercado', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 12, 'state_id' => 1, 'name' => 'Provincia General José Ballivián', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 13, 'state_id' => 1, 'name' => 'Provincia Iténez', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 14, 'state_id' => 1, 'name' => 'Provincia Mamoré', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 15, 'state_id' => 1, 'name' => 'Provincia Marbán', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 16, 'state_id' => 1, 'name' => 'Provincia Moxos', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 17, 'state_id' => 1, 'name' => 'Provincia Vaca Diez', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 18, 'state_id' => 1, 'name' => 'Provincia Yacuma', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 19, 'state_id' => 1, 'name' => 'Reyes', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 20, 'state_id' => 1, 'name' => 'Riberalta', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 21, 'state_id' => 1, 'name' => 'Rurrenabaque', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 22, 'state_id' => 1, 'name' => 'San Borja', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 23, 'state_id' => 1, 'name' => 'San Ramón', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 24, 'state_id' => 1, 'name' => 'Santa Ana de Yacuma', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 25, 'state_id' => 1, 'name' => 'Santa Rosa', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 26, 'state_id' => 1, 'name' => 'Trinidad', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 27, 'state_id' => 2, 'name' => 'Challapata', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 28, 'state_id' => 2, 'name' => 'Huanuni', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 29, 'state_id' => 2, 'name' => 'Litoral de Atacama', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 30, 'state_id' => 2, 'name' => 'Machacamarca', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 31, 'state_id' => 2, 'name' => 'Nor Carangas Province', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 32, 'state_id' => 2, 'name' => 'Oruro', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 33, 'state_id' => 2, 'name' => 'Poopó', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 34, 'state_id' => 2, 'name' => 'Provincia Avaroa', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 35, 'state_id' => 2, 'name' => 'Provincia Carangas', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 36, 'state_id' => 2, 'name' => 'Provincia Cercado', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 37, 'state_id' => 2, 'name' => 'Provincia Ladislao Cabrera', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 38, 'state_id' => 2, 'name' => 'Provincia Pantaleón Dalence', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 39, 'state_id' => 2, 'name' => 'Provincia Poopó', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 40, 'state_id' => 2, 'name' => 'Provincia Sabaya', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 41, 'state_id' => 2, 'name' => 'Provincia Sajama', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 42, 'state_id' => 2, 'name' => 'Provincia San Pedro de Totora', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 43, 'state_id' => 2, 'name' => 'Provincia Saucari', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 44, 'state_id' => 2, 'name' => 'Provincia Tomás Barron', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 45, 'state_id' => 2, 'name' => 'Puerto de Mejillones', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 46, 'state_id' => 2, 'name' => 'Sebastian Pagador Province', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 47, 'state_id' => 2, 'name' => 'Sud Carangas Province', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 48, 'state_id' => 2, 'name' => 'Totoral', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 49, 'state_id' => 4, 'name' => 'Bermejo', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 50, 'state_id' => 4, 'name' => 'Entre Ríos', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 51, 'state_id' => 4, 'name' => 'Provincia Arce', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 52, 'state_id' => 4, 'name' => 'Provincia Avilez', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 53, 'state_id' => 4, 'name' => 'Provincia Cercado', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 54, 'state_id' => 4, 'name' => 'Provincia Gran Chaco', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 55, 'state_id' => 4, 'name' => 'Provincia Méndez', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 56, 'state_id' => 4, 'name' => 'Provincia O’Connor', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 57, 'state_id' => 4, 'name' => 'Tarija', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 58, 'state_id' => 4, 'name' => 'Villamontes', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 59, 'state_id' => 4, 'name' => 'Yacuiba', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 60, 'state_id' => 5, 'name' => 'Cobija', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 61, 'state_id' => 5, 'name' => 'Provincia Abuná', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 62, 'state_id' => 5, 'name' => 'Provincia General Federico Román', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 63, 'state_id' => 5, 'name' => 'Provincia Madre de Dios', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 64, 'state_id' => 5, 'name' => 'Provincia Manuripi', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 65, 'state_id' => 5, 'name' => 'Provincia Nicolás Suárez', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 66, 'state_id' => 6, 'name' => 'Achacachi', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 67, 'state_id' => 6, 'name' => 'Amarete', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 68, 'state_id' => 6, 'name' => 'Batallas', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 69, 'state_id' => 6, 'name' => 'Caranavi', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 70, 'state_id' => 6, 'name' => 'Chulumani', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 71, 'state_id' => 6, 'name' => 'Colquiri', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 72, 'state_id' => 6, 'name' => 'Coripata', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 73, 'state_id' => 6, 'name' => 'Coroico', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 74, 'state_id' => 6, 'name' => 'Curahuara de Carangas', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 75, 'state_id' => 6, 'name' => 'Eucaliptus', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 76, 'state_id' => 6, 'name' => 'Guanay', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 77, 'state_id' => 6, 'name' => 'Huarina', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 78, 'state_id' => 6, 'name' => 'Huatajata', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 79, 'state_id' => 6, 'name' => 'José Manuel Pando', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 80, 'state_id' => 6, 'name' => 'La Paz', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 81, 'state_id' => 6, 'name' => 'Lahuachaca', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 82, 'state_id' => 6, 'name' => 'Mapiri', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 83, 'state_id' => 6, 'name' => 'Patacamaya', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 84, 'state_id' => 6, 'name' => 'Provincia Aroma', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 85, 'state_id' => 6, 'name' => 'Provincia Bautista Saavedra', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 86, 'state_id' => 6, 'name' => 'Provincia Camacho', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 87, 'state_id' => 6, 'name' => 'Provincia Franz Tamayo', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 88, 'state_id' => 6, 'name' => 'Provincia Gualberto Villarroel', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 89, 'state_id' => 6, 'name' => 'Provincia Ingavi', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 90, 'state_id' => 6, 'name' => 'Provincia Inquisivi', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 91, 'state_id' => 6, 'name' => 'Provincia Iturralde', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 92, 'state_id' => 6, 'name' => 'Provincia Larecaja', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 93, 'state_id' => 6, 'name' => 'Provincia Loayza', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 94, 'state_id' => 6, 'name' => 'Provincia Los Andes', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 95, 'state_id' => 6, 'name' => 'Provincia Manco Kapac', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 96, 'state_id' => 6, 'name' => 'Provincia Murillo', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 97, 'state_id' => 6, 'name' => 'Provincia Muñecas', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 98, 'state_id' => 6, 'name' => 'Provincia Nor Yungas', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 99, 'state_id' => 6, 'name' => 'Provincia Omasuyos', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 100, 'state_id' => 6, 'name' => 'Provincia Pacajes', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 101, 'state_id' => 6, 'name' => 'Provincia Sud Yungas', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 102, 'state_id' => 6, 'name' => 'Quime', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 103, 'state_id' => 6, 'name' => 'San Pablo', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 104, 'state_id' => 6, 'name' => 'San Pedro', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 105, 'state_id' => 6, 'name' => 'Sorata', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 106, 'state_id' => 6, 'name' => 'Tiahuanaco', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 107, 'state_id' => 6, 'name' => 'Viloco', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 108, 'state_id' => 6, 'name' => 'Yumani', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 109, 'state_id' => 7, 'name' => 'Aiquile', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 110, 'state_id' => 7, 'name' => 'Arani', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 111, 'state_id' => 7, 'name' => 'Bolivar', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 112, 'state_id' => 7, 'name' => 'Capinota', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 113, 'state_id' => 7, 'name' => 'Chimoré', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 114, 'state_id' => 7, 'name' => 'Cliza', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 115, 'state_id' => 7, 'name' => 'Cochabamba', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 116, 'state_id' => 7, 'name' => 'Colchani', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 117, 'state_id' => 7, 'name' => 'Colomi', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 118, 'state_id' => 7, 'name' => 'Independencia', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 119, 'state_id' => 7, 'name' => 'Irpa Irpa', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 120, 'state_id' => 7, 'name' => 'Mizque', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 121, 'state_id' => 7, 'name' => 'Provincia Arani', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 122, 'state_id' => 7, 'name' => 'Provincia Arque', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 123, 'state_id' => 7, 'name' => 'Provincia Ayopaya', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 124, 'state_id' => 7, 'name' => 'Provincia Campero', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 125, 'state_id' => 7, 'name' => 'Provincia Capinota', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 126, 'state_id' => 7, 'name' => 'Provincia Carrasco', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 127, 'state_id' => 7, 'name' => 'Provincia Cercado', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 128, 'state_id' => 7, 'name' => 'Provincia Chaparé', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 129, 'state_id' => 7, 'name' => 'Provincia Esteban Arce', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 130, 'state_id' => 7, 'name' => 'Provincia Germán Jordán', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 131, 'state_id' => 7, 'name' => 'Provincia Mizque', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 132, 'state_id' => 7, 'name' => 'Provincia Punata', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 133, 'state_id' => 7, 'name' => 'Provincia Quillacollo', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 134, 'state_id' => 7, 'name' => 'Provincia Tapacarí', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 135, 'state_id' => 7, 'name' => 'Punata', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 136, 'state_id' => 7, 'name' => 'Quillacollo', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 137, 'state_id' => 7, 'name' => 'Sacaba', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 138, 'state_id' => 7, 'name' => 'Sipe Sipe', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 139, 'state_id' => 7, 'name' => 'Tarata', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 140, 'state_id' => 7, 'name' => 'Tiquipaya', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 141, 'state_id' => 7, 'name' => 'Tiraque Province', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 142, 'state_id' => 7, 'name' => 'Totora', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 143, 'state_id' => 8, 'name' => 'Camargo', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 144, 'state_id' => 8, 'name' => 'Monteagudo', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 145, 'state_id' => 8, 'name' => 'Padilla', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 146, 'state_id' => 8, 'name' => 'Provincia Azurduy', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 147, 'state_id' => 8, 'name' => 'Provincia Belisario Boeto', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 148, 'state_id' => 8, 'name' => 'Provincia Hernando Siles', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 149, 'state_id' => 8, 'name' => 'Provincia Luis Calvo', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 150, 'state_id' => 8, 'name' => 'Provincia Nor Cinti', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 151, 'state_id' => 8, 'name' => 'Provincia Oropeza', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 152, 'state_id' => 8, 'name' => 'Provincia Sud Cinti', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 153, 'state_id' => 8, 'name' => 'Provincia Tomina', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 154, 'state_id' => 8, 'name' => 'Provincia Yamparáez', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 155, 'state_id' => 8, 'name' => 'Provincia Zudáñez', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 156, 'state_id' => 8, 'name' => 'Sucre', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 157, 'state_id' => 8, 'name' => 'Tarabuco', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 158, 'state_id' => 9, 'name' => 'Atocha', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 159, 'state_id' => 9, 'name' => 'Betanzos', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 160, 'state_id' => 9, 'name' => 'Colchani', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 161, 'state_id' => 9, 'name' => 'Colquechaca', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 162, 'state_id' => 9, 'name' => 'Enrique Baldivieso', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 163, 'state_id' => 9, 'name' => 'Llallagua', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 164, 'state_id' => 9, 'name' => 'Potosí', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 165, 'state_id' => 9, 'name' => 'Provincia Alonzo de Ibáñez', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 166, 'state_id' => 9, 'name' => 'Provincia Charcas', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 167, 'state_id' => 9, 'name' => 'Provincia Chayanta', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 168, 'state_id' => 9, 'name' => 'Provincia Daniel Campos', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 169, 'state_id' => 9, 'name' => 'Provincia General Bilbao', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 170, 'state_id' => 9, 'name' => 'Provincia Linares', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 171, 'state_id' => 9, 'name' => 'Provincia Modesto Omiste', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 172, 'state_id' => 9, 'name' => 'Provincia Nor Chichas', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 173, 'state_id' => 9, 'name' => 'Provincia Nor Lípez', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 174, 'state_id' => 9, 'name' => 'Provincia Quijarro', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 175, 'state_id' => 9, 'name' => 'Provincia Rafael Bustillo', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 176, 'state_id' => 9, 'name' => 'Provincia Saavedra', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 177, 'state_id' => 9, 'name' => 'Provincia Sud Chichas', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 178, 'state_id' => 9, 'name' => 'Provincia Sud Lípez', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 179, 'state_id' => 9, 'name' => 'Provincia Tomás Frías', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 180, 'state_id' => 9, 'name' => 'Santa Bárbara', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 181, 'state_id' => 9, 'name' => 'Tupiza', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 182, 'state_id' => 9, 'name' => 'Uyuni', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 183, 'state_id' => 9, 'name' => 'Villazón', 'created_at' => now(), 'updated_at' => now(), ],

            [ 'id' => 	184	, 'state_id' => 	10	, 'name' => '	Armenia	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	185	, 'state_id' => 	10	, 'name' => '	Buenavista	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	186	, 'state_id' => 	10	, 'name' => '	Calarca	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	187	, 'state_id' => 	10	, 'name' => '	Circasia	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	188	, 'state_id' => 	10	, 'name' => '	Córdoba	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	189	, 'state_id' => 	10	, 'name' => '	Filandia	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	190	, 'state_id' => 	10	, 'name' => '	Génova	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	191	, 'state_id' => 	10	, 'name' => '	La Tebaida	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	192	, 'state_id' => 	10	, 'name' => '	Montenegro	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	193	, 'state_id' => 	10	, 'name' => '	Pijao	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	194	, 'state_id' => 	10	, 'name' => '	Quimbaya	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	195	, 'state_id' => 	10	, 'name' => '	Salento	', 'created_at' => now(), 'updated_at' => now(), ],

            [ 'id' => 	196	, 'state_id' => 	11	, 'name' => '	Agua de Dios	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	197	, 'state_id' => 	11	, 'name' => '	Albán	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	198	, 'state_id' => 	11	, 'name' => '	Anapoima	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	199	, 'state_id' => 	11	, 'name' => '	Anolaima	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	200	, 'state_id' => 	11	, 'name' => '	Apulo	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	201	, 'state_id' => 	11	, 'name' => '	Arbeláez	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	202	, 'state_id' => 	11	, 'name' => '	Beltrán	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	203	, 'state_id' => 	11	, 'name' => '	Bituima	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	204	, 'state_id' => 	11	, 'name' => '	Bojacá	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	205	, 'state_id' => 	11	, 'name' => '	Cabrera	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	206	, 'state_id' => 	11	, 'name' => '	Cachipay	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	207	, 'state_id' => 	11	, 'name' => '	Cajicá	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	208	, 'state_id' => 	11	, 'name' => '	Caparrapí	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	209	, 'state_id' => 	11	, 'name' => '	Caqueza	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	210	, 'state_id' => 	11	, 'name' => '	Carmen de Carupa	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	211	, 'state_id' => 	11	, 'name' => '	Chaguaní	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	212	, 'state_id' => 	11	, 'name' => '	Chipaque	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	213	, 'state_id' => 	11	, 'name' => '	Choachí	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	214	, 'state_id' => 	11	, 'name' => '	Chocontá	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	215	, 'state_id' => 	11	, 'name' => '	Chía	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	216	, 'state_id' => 	11	, 'name' => '	Cogua	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	217	, 'state_id' => 	11	, 'name' => '	Cota	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	218	, 'state_id' => 	11	, 'name' => '	Cucunubá	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	219	, 'state_id' => 	11	, 'name' => '	El Colegio	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	220	, 'state_id' => 	11	, 'name' => '	El Peñón	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	221	, 'state_id' => 	11	, 'name' => '	El Rosal	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	222	, 'state_id' => 	11	, 'name' => '	Facatativá	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	223	, 'state_id' => 	11	, 'name' => '	Fomeque	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	224	, 'state_id' => 	11	, 'name' => '	Fosca	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	225	, 'state_id' => 	11	, 'name' => '	Funza	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	226	, 'state_id' => 	11	, 'name' => '	Fusagasugá	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	227	, 'state_id' => 	11	, 'name' => '	Fúquene	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	228	, 'state_id' => 	11	, 'name' => '	Gachala	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	229	, 'state_id' => 	11	, 'name' => '	Gachancipá	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	230	, 'state_id' => 	11	, 'name' => '	Gachetá	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	231	, 'state_id' => 	11	, 'name' => '	Gama	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	232	, 'state_id' => 	11	, 'name' => '	Girardot	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	233	, 'state_id' => 	11	, 'name' => '	Granada	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	234	, 'state_id' => 	11	, 'name' => '	Guachetá	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	235	, 'state_id' => 	11	, 'name' => '	Guaduas	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	236	, 'state_id' => 	11	, 'name' => '	Guasca	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	237	, 'state_id' => 	11	, 'name' => '	Guataquí	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	238	, 'state_id' => 	11	, 'name' => '	Guatavita	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	239	, 'state_id' => 	11	, 'name' => '	Guayabal de Siquima	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	240	, 'state_id' => 	11	, 'name' => '	Guayabetal	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	241	, 'state_id' => 	11	, 'name' => '	Gutiérrez	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	242	, 'state_id' => 	11	, 'name' => '	Jerusalén	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	243	, 'state_id' => 	11	, 'name' => '	Junín	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	244	, 'state_id' => 	11	, 'name' => '	La Calera	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	245	, 'state_id' => 	11	, 'name' => '	La Mesa	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	246	, 'state_id' => 	11	, 'name' => '	La Palma	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	247	, 'state_id' => 	11	, 'name' => '	La Peña	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	248	, 'state_id' => 	11	, 'name' => '	La Vega	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	249	, 'state_id' => 	11	, 'name' => '	Lenguazaque	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	250	, 'state_id' => 	11	, 'name' => '	Macheta	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	251	, 'state_id' => 	11	, 'name' => '	Madrid	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	252	, 'state_id' => 	11	, 'name' => '	Manta	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	253	, 'state_id' => 	11	, 'name' => '	Medina	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	254	, 'state_id' => 	11	, 'name' => '	Mosquera	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	255	, 'state_id' => 	11	, 'name' => '	Nariño	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	256	, 'state_id' => 	11	, 'name' => '	Nemocón	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	257	, 'state_id' => 	11	, 'name' => '	Nilo	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	258	, 'state_id' => 	11	, 'name' => '	Nimaima	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	259	, 'state_id' => 	11	, 'name' => '	Nocaima	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	260	, 'state_id' => 	11	, 'name' => '	Pacho	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	261	, 'state_id' => 	11	, 'name' => '	Paime	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	262	, 'state_id' => 	11	, 'name' => '	Pandi	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	263	, 'state_id' => 	11	, 'name' => '	Paratebueno	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	264	, 'state_id' => 	11	, 'name' => '	Pasca	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	265	, 'state_id' => 	11	, 'name' => '	Puerto Salgar	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	266	, 'state_id' => 	11	, 'name' => '	Pulí	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	267	, 'state_id' => 	11	, 'name' => '	Quebradanegra	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	268	, 'state_id' => 	11	, 'name' => '	Quetame	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	269	, 'state_id' => 	11	, 'name' => '	Quipile	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	270	, 'state_id' => 	11	, 'name' => '	Ricaurte	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	271	, 'state_id' => 	11	, 'name' => '	San Antonio del Tequendama	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	272	, 'state_id' => 	11	, 'name' => '	San Bernardo	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	273	, 'state_id' => 	11	, 'name' => '	San Cayetano	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	274	, 'state_id' => 	11	, 'name' => '	San Francisco	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	275	, 'state_id' => 	11	, 'name' => '	San Juan de Río Seco	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	276	, 'state_id' => 	11	, 'name' => '	Sasaima	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	277	, 'state_id' => 	11	, 'name' => '	Sesquilé	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	278	, 'state_id' => 	11	, 'name' => '	Sibaté	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	279	, 'state_id' => 	11	, 'name' => '	Silvania	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	280	, 'state_id' => 	11	, 'name' => '	Simijaca	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	281	, 'state_id' => 	11	, 'name' => '	Soacha	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	282	, 'state_id' => 	11	, 'name' => '	Sopó	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	283	, 'state_id' => 	11	, 'name' => '	Subachoque	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	284	, 'state_id' => 	11	, 'name' => '	Suesca	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	285	, 'state_id' => 	11	, 'name' => '	Supatá	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	286	, 'state_id' => 	11	, 'name' => '	Susa	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	287	, 'state_id' => 	11	, 'name' => '	Sutatausa	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	288	, 'state_id' => 	11	, 'name' => '	Tabio	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	289	, 'state_id' => 	11	, 'name' => '	Tausa	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	290	, 'state_id' => 	11	, 'name' => '	Tena	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	291	, 'state_id' => 	11	, 'name' => '	Tenjo	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	292	, 'state_id' => 	11	, 'name' => '	Tibacuy	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	293	, 'state_id' => 	11	, 'name' => '	Tibirita	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	294	, 'state_id' => 	11	, 'name' => '	Tocaima	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	295	, 'state_id' => 	11	, 'name' => '	Tocancipá	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	296	, 'state_id' => 	11	, 'name' => '	Topaipí	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	297	, 'state_id' => 	11	, 'name' => '	Ubalá	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	298	, 'state_id' => 	11	, 'name' => '	Ubaque	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	299	, 'state_id' => 	11	, 'name' => '	Une	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	300	, 'state_id' => 	11	, 'name' => '	Venecia	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	301	, 'state_id' => 	11	, 'name' => '	Vergara	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	302	, 'state_id' => 	11	, 'name' => '	Vianí	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	303	, 'state_id' => 	11	, 'name' => '	Villa de San Diego de Ubate	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	304	, 'state_id' => 	11	, 'name' => '	Villagómez	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	305	, 'state_id' => 	11	, 'name' => '	Villapinzón	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	306	, 'state_id' => 	11	, 'name' => '	Villeta	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	307	, 'state_id' => 	11	, 'name' => '	Viotá	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	308	, 'state_id' => 	11	, 'name' => '	Yacopí	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	309	, 'state_id' => 	11	, 'name' => '	Zipacón	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	310	, 'state_id' => 	11	, 'name' => '	Zipaquirá	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	311	, 'state_id' => 	11	, 'name' => '	Útica	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	312	, 'state_id' => 	11	, 'name' => '	Bogotá D.C.	', 'created_at' => now(), 'updated_at' => now(), ],

            [ 'id' => 	313	, 'state_id' => 	12	, 'name' => '	Acandí	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	314	, 'state_id' => 	12	, 'name' => '	Alto Baudó	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	315	, 'state_id' => 	12	, 'name' => '	Atrato	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	316	, 'state_id' => 	12	, 'name' => '	Bagadó	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	317	, 'state_id' => 	12	, 'name' => '	Bahía Solano	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	318	, 'state_id' => 	12	, 'name' => '	Bajo Baudó	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	319	, 'state_id' => 	12	, 'name' => '	Bojayá	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	320	, 'state_id' => 	12	, 'name' => '	Carmen del Darien	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	321	, 'state_id' => 	12	, 'name' => '	Condoto	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	322	, 'state_id' => 	12	, 'name' => '	Cértegui	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	323	, 'state_id' => 	12	, 'name' => '	El Cantón de San Pablo	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	324	, 'state_id' => 	12	, 'name' => '	El Carmen de Atrato	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	325	, 'state_id' => 	12	, 'name' => '	Istmina	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	326	, 'state_id' => 	12	, 'name' => '	Juradó	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	327	, 'state_id' => 	12	, 'name' => '	Lloró	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	328	, 'state_id' => 	12	, 'name' => '	Medio Atrato	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	329	, 'state_id' => 	12	, 'name' => '	Medio Baudó	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	330	, 'state_id' => 	12	, 'name' => '	Medio San Juan	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	331	, 'state_id' => 	12	, 'name' => '	Nuquí	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	332	, 'state_id' => 	12	, 'name' => '	Nóvita	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	333	, 'state_id' => 	12	, 'name' => '	Quibdó	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	334	, 'state_id' => 	12	, 'name' => '	Riosucio	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	335	, 'state_id' => 	12	, 'name' => '	Río Iro	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	336	, 'state_id' => 	12	, 'name' => '	Río Quito	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	337	, 'state_id' => 	12	, 'name' => '	San José del Palmar	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	338	, 'state_id' => 	12	, 'name' => '	Litoral del San Juan	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	339	, 'state_id' => 	12	, 'name' => '	Sipí	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	340	, 'state_id' => 	12	, 'name' => '	Tadó	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	341	, 'state_id' => 	12	, 'name' => '	Unguía	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	342	, 'state_id' => 	12	, 'name' => '	Unión Panamericana	', 'created_at' => now(), 'updated_at' => now(), ],

            [ 'id' => 	343	, 'state_id' => 	13	, 'name' => '	Abrego	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	344	, 'state_id' => 	13	, 'name' => '	Arboledas	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	345	, 'state_id' => 	13	, 'name' => '	Bochalema	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	346	, 'state_id' => 	13	, 'name' => '	Bucarasica	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	347	, 'state_id' => 	13	, 'name' => '	Cachirá	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	348	, 'state_id' => 	13	, 'name' => '	Chinácota	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	349	, 'state_id' => 	13	, 'name' => '	Chitagá	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	350	, 'state_id' => 	13	, 'name' => '	Convención	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	351	, 'state_id' => 	13	, 'name' => '	Cucutilla	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	352	, 'state_id' => 	13	, 'name' => '	Cácota	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	353	, 'state_id' => 	13	, 'name' => '	Cúcuta	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	354	, 'state_id' => 	13	, 'name' => '	Durania	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	355	, 'state_id' => 	13	, 'name' => '	El Carmen	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	356	, 'state_id' => 	13	, 'name' => '	El Tarra	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	357	, 'state_id' => 	13	, 'name' => '	El Zulia	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	358	, 'state_id' => 	13	, 'name' => '	Gramalote	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	359	, 'state_id' => 	13	, 'name' => '	Hacarí	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	360	, 'state_id' => 	13	, 'name' => '	Herrán	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	361	, 'state_id' => 	13	, 'name' => '	La Esperanza	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	362	, 'state_id' => 	13	, 'name' => '	La Playa	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	363	, 'state_id' => 	13	, 'name' => '	Labateca	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	364	, 'state_id' => 	13	, 'name' => '	Los Patios	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	365	, 'state_id' => 	13	, 'name' => '	Lourdes	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	366	, 'state_id' => 	13	, 'name' => '	Mutiscua	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	367	, 'state_id' => 	13	, 'name' => '	Ocaña	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	368	, 'state_id' => 	13	, 'name' => '	Pamplona	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	369	, 'state_id' => 	13	, 'name' => '	Pamplonita	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	370	, 'state_id' => 	13	, 'name' => '	Puerto Santander	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	371	, 'state_id' => 	13	, 'name' => '	Ragonvalia	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	372	, 'state_id' => 	13	, 'name' => '	Salazar	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	373	, 'state_id' => 	13	, 'name' => '	San Calixto	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	374	, 'state_id' => 	13	, 'name' => '	San Cayetano	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	375	, 'state_id' => 	13	, 'name' => '	Santiago	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	376	, 'state_id' => 	13	, 'name' => '	Sardinata	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	377	, 'state_id' => 	13	, 'name' => '	Silos	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	378	, 'state_id' => 	13	, 'name' => '	Tibú	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	379	, 'state_id' => 	13	, 'name' => '	Toledo	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	380	, 'state_id' => 	13	, 'name' => '	Villa del Rosario	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	381	, 'state_id' => 	13	, 'name' => '	Teorama	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	382	, 'state_id' => 	13	, 'name' => '	Villa Caro	', 'created_at' => now(), 'updated_at' => now(), ],

            [ 'id' => 	383	, 'state_id' => 	14	, 'name' => '	Acacías	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	384	, 'state_id' => 	14	, 'name' => '	Barranca de Upía	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	385	, 'state_id' => 	14	, 'name' => '	Cabuyaro	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	386	, 'state_id' => 	14	, 'name' => '	Castilla la Nueva	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	387	, 'state_id' => 	14	, 'name' => '	Cubarral	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	388	, 'state_id' => 	14	, 'name' => '	Cumaral	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	389	, 'state_id' => 	14	, 'name' => '	El Calvario	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	390	, 'state_id' => 	14	, 'name' => '	El Castillo	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	391	, 'state_id' => 	14	, 'name' => '	Fuente de Oro	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	392	, 'state_id' => 	14	, 'name' => '	Granada	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	393	, 'state_id' => 	14	, 'name' => '	Guamal	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	394	, 'state_id' => 	14	, 'name' => '	La Macarena	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	395	, 'state_id' => 	14	, 'name' => '	Lejanías	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	396	, 'state_id' => 	14	, 'name' => '	Mapiripán	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	397	, 'state_id' => 	14	, 'name' => '	Mesetas	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	398	, 'state_id' => 	14	, 'name' => '	Puerto Concordia	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	399	, 'state_id' => 	14	, 'name' => '	Puerto Gaitán	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	400	, 'state_id' => 	14	, 'name' => '	Puerto Lleras	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	401	, 'state_id' => 	14	, 'name' => '	Puerto López	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	402	, 'state_id' => 	14	, 'name' => '	Puerto Rico	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	403	, 'state_id' => 	14	, 'name' => '	Restrepo	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	404	, 'state_id' => 	14	, 'name' => '	San Carlos de Guaroa	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	405	, 'state_id' => 	14	, 'name' => '	San Juan de Arama	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	406	, 'state_id' => 	14	, 'name' => '	San Martín	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	407	, 'state_id' => 	14	, 'name' => '	Villavicencio	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	408	, 'state_id' => 	14	, 'name' => '	Vistahermosa	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	409	, 'state_id' => 	14	, 'name' => '	El Dorado	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	410	, 'state_id' => 	14	, 'name' => '	San Juanito	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	411	, 'state_id' => 	14	, 'name' => '	Uribe	', 'created_at' => now(), 'updated_at' => now(), ],

            [ 'id' => 	412	, 'state_id' => 	15	, 'name' => '	Apía	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	413	, 'state_id' => 	15	, 'name' => '	Balboa	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	414	, 'state_id' => 	15	, 'name' => '	Belén de Umbría	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	415	, 'state_id' => 	15	, 'name' => '	Dosquebradas	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	416	, 'state_id' => 	15	, 'name' => '	Guática	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	417	, 'state_id' => 	15	, 'name' => '	La Celia	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	418	, 'state_id' => 	15	, 'name' => '	La Virginia	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	419	, 'state_id' => 	15	, 'name' => '	Marsella	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	420	, 'state_id' => 	15	, 'name' => '	Mistrató	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	421	, 'state_id' => 	15	, 'name' => '	Pereira	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	422	, 'state_id' => 	15	, 'name' => '	Pueblo Rico	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	423	, 'state_id' => 	15	, 'name' => '	Quinchía	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	424	, 'state_id' => 	15	, 'name' => '	Santa Rosa de Cabal	', 'created_at' => now(), 'updated_at' => now(), ],
            [ 'id' => 	425	, 'state_id' => 	15	, 'name' => '	Santuario	', 'created_at' => now(), 'updated_at' => now(), ],

        ];
        city::insert($cities);
    }
}
